[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "setuptools_scm[toml]>=8.0",
    "pybind11>=2.6",
    "scikit-build-core>=0.5",
]
build-backend = "scikit_build_core.build"

[project]
name = "jax-finufft"
description = "Unofficial JAX bindings for finufft"
readme = "README.md"
authors = [{name = "Dan Foreman-Mackey", email = "foreman.mackey@gmail.com"}]
requires-python = ">=3.7"
license = {file = "LICENSE"}
urls = {Homepage = "https://github.com/dfm/jax-finufft"}
dependencies = [
    "jax",
    "jaxlib",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/jax_finufft/jax_finufft_version.py"]
wheel.install-dir = "jax_finufft"
minimum-version = "0.5"
build-dir = "build/{wheel_tag}"

[tool.setuptools_scm]
version_file = "src/jax_finufft/jax_finufft_version.py"

[tool.isort]
profile = "black"
